### PR TITLE
Sort body tables

### PR DESCRIPTION
**Pull request by MarcelBolten**
https://github.com/elabftw/elabftw/pull/3852

### CODE REVIEW

**Review by NicolasCARPi — APPROVED** [review]

**Comment by NicolasCARPi** [comment]
cheers, forgot about this one!

**Comment by MarcelBolten** [comment]
Oh, yes. Me too.
This needs a little update. Compare to https://github.com/elabftw/elabftw/pull/3852#issuecomment-1334608974

**Comment by NicolasCARPi** [comment]
> This needs a little update

Waiting for a PR then ;)

**Comment by MarcelBolten** [comment]
I will try to make a comprehensive video/gif and update the text.

**Pull request merged**
